### ISSUE TITLE
CrunchySubs ya no descarga los Subtitulos 

### ISSUE THREAD

**Issue by Solus32** [7ouma/CrunchySubs#2]
Crunchyroll ha hecho cambios en su sistema por lo que el script ha dejado de funcionar, ya intente con muchos links, y con animes viejos y da este error:

El enlace ingresado es incorrecto. 

Usando CrunchySubs versión 1.3.3

**Comment by Solus32** [comment]
Y con la Version 1.4 Beta da este error:

Error: El enlace ingresado no es de Crunchyroll/Videos.
Error: El enlace ingresado no es de Crunchyroll/Videos.

**Comment by karurosu15** [comment]
A mi tambien me da error al bajar los sub con la 1.3.3. ¿Cual es la version 1.4 beta?

**Comment by Solus32** [comment]
La última versión que subió 7ouma en Github es la Versión 1.4 Beta.
Yo lo probé con la Versión 1.3.3 y la Versión 1.4 Beta.
El Script ya no funciona más.

**Comment by 7ouma** [comment]
> La última versión que subió 7ouma en Github es la Versión 1.4 Beta.
> Yo lo probé con la Versión 1.3.3 y la Versión 1.4 Beta.
> El Script ya no funciona más.

Hmm, acabo de probar el script con el capítulo 

https://www.crunchyroll.com/mob-psycho-100/episode-1-ripped-apart-someone-is-watching-780920 

y no me dio ningún inconveniente. Igual probé 3 capítulos más y no tuve problemas. 


¿Cuáles son los enlaces con los que andas probando?

**Comment by Solus32** [comment]
Mmm, curioso, tu link que me diste si aparece la opción de descarga.

Pero estos no quiere:

https://www.crunchyroll.com/es/the-rising-of-the-shield-hero/episode-2-the-slave-girl-781149

https://www.crunchyroll.com/es/one-piece/episode-869-wake-up-the-color-of-observation-able-to-top-the-strongest-781888

Creo que ya encontré el Problema.

Al parecer si entro en Crunchyroll en Español ; https://www.crunchyroll.com/es/ no permite la descarga , pero si entro en el sitio en Ingles de Estados Unidos si me permite descargar.

Anteriormente con los links de Crunchyroll del sitio en español permitía la descarga.

Enlace de Crunchyroll de Estados Unidos

https://www.crunchyroll.com/the-rising-of-the-shield-hero/episode-2-the-slave-girl-781149

**Comment by 7ouma** [comment]
Listo, ya agregué una condición para que permita esos enlaces. 

https://github.com/7ouma/CrunchySubs/commit/86a72e26a78ca71994108447f8d1662a240f3752

Descarga la última versión del script https://github.com/7ouma/CrunchySubs/blob/master/CrunchySubs.py

Saludos.

**Comment by Solus32** [comment]
Ok , Muchas Gracias, te lo agradezco muchísimo.

Si ya está funcionando a la perfección

Saludos.

**Comment by GustavoSerra21** [comment]
Como es el comando para iniciar el programa? 
Y aun sigue funcionado?
