### ISSUE TITLE
Nuevo Error al Descargar Subtitulos

### ISSUE THREAD

**Issue by Solus32** [7ouma/CrunchySubs#3]
El día de hoy me salió un nuevo error al descargar los subtitulos. 

Descargue  primero el  subtitulo en Windows, al poner el enlace y dar enter se cerró la ventana sin marcar error ni nada. Pero en Linux me apareció esto:

solus@desktop:~$ CrunchySubs
Opciones:
1.- Descargar
2.- Descargar paquete de enlaces
3.- Login
4.- Configuración
5.- Acerca de
0.- Salir
>1
Introduce el enlace: https://www.crunchyroll.com/the-rising-of-the-shield-hero/episode-8-curse-shield-781155
Traceback (most recent call last):
  File "CrunchySubs.py", line 483, in <module>
    url = subs.UrlCheck(str(raw_input("Introduce el enlace: ")))
  File "CrunchySubs.py", line 433, in UrlCheck
    soup = BeautifulSoup(xml)
  File "/home/solus/CrunchySubs/BeautifulSoup.py", line 1517, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/home/solus/CrunchySubs/BeautifulSoup.py", line 1142, in __init__
    self._feed(isHTML=isHTML)
  File "/home/solus/CrunchySubs/BeautifulSoup.py", line 1166, in _feed
    smartQuotesTo=self.smartQuotesTo, isHTML=isHTML)
  File "/home/solus/CrunchySubs/BeautifulSoup.py", line 1768, in __init__
    self._detectEncoding(markup, isHTML)
  File "/home/solus/CrunchySubs/BeautifulSoup.py", line 1913, in _detectEncoding
    '^<\?.*encoding=[\'"](.*?)[\'"].*\?>').match(xml_data)
TypeError: expected string or buffer

Y de igual manera probé con links de Estados Unidos, y del Sitio en español, con links viejos y nuevos y fue igual, el mismo error.

El día de ayer descargue Subtitulos sin ningún problema.
Saludos.

**Comment by Solus32** [comment]
Tendrá algo que ver el que CrunchyRoll use ahora DDoS de Cloudflare? y que tarde más tiempo en desplegar la página web.

**Comment by Solus32** [comment]
Al parecer para que pueda funcionar de nuevo el Script se necesita instalar y agregar NodeJS al script para que funcione con CloudFlare.

**Comment by rs3mk** [comment]
falta esto https://pypi.python.org/pypi/cfscrape/ que a su vez pide nodejs

**Comment by 7ouma** [comment]
Ya se encuentra solucionado el error
https://github.com/7ouma/CrunchySubs/commit/ebae7a60517a9fedc3bdf52631cc853d9760cdd6

Solo deben de actualizar a la última versión del script, e instalar cfscrape. Fue relativamente fácil de implementar ya que CrunchyManga ya tenía soporte de cloudflare desde hace dos años. 

Esta semana trabajo en el login, que por lo que veo no está funcionado, pero eso sería enfocado en CrunchyManga, porque acá creo que el login ya no hace falta. De hecho, no es necesario, se añadió porque hubo un tiempo que necesitabas cuenta premium para bajar los subs de capítulos premium. 


Saludos.

**Comment by THeXES** [comment]
Buenas 7ouma, ¿tienes pensado sacar el .exe de la versión corregida? 

Con el actual se cierra al poner el Link para pasar a la selección de descarga de Subtítulos...

Edito:

@7ouma Sería de la parte Anime... Me indica que se está usando Python 3.7.2 pero le puse el que recomiendas y lo mismo; hasta hace unas semanas iba perfecto y no cambié nada a priori.

Me pasa con todos los enlaces en estos momentos... A mí desde Python me da (instalé lo necesario):  

-   File "<stdin>", line 1
-     C:\Users\Downloads\CrunchySubs-master\CrunchySubs-master\CrunchySubs.py
-      ^
- SyntaxError: invalid syntax

Gracias por adelantado!

**Comment by 7ouma** [comment]
Qué tal @THeXES , me puedes indicar con qué enlace se te cae? Hice pruebas con varios capítulos al azar de series y todas me descargaron. Debes tener pyton 2.7.* instalado, nodejs y cfscrape para que funcione bien. 

Lo del exe tendría que estudiarlo, hace bastante deje de sacar exe en CrunchyManga porque daba error al hacerlo después de añadir cfscrape, tendría que ver bien el caso cuando tenga tiempo libre.

**Comment by Solus32** [comment]
Hola @7ouma Fijate que me sale error a mi.

C:\Users\solus\CrunchySubs>CrunchySubs
  File "CrunchySubs.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Ya instale cfscrape y NodeJS version 10.15.3

Ahorita estoy Usando Windows 10 1809 x64

**Comment by 7ouma** [comment]
> Hola @7ouma Fijate que me sale error a mi.
> 
> C:\Users\solus\CrunchySubs>python CrunchySubs.py
> File "CrunchySubs.py", line 7
> 
> ^
> SyntaxError: invalid syntax
> 
> Ya instale cfscrape y NodeJS version 10.15.3
> 
> Ahorita estoy Usando Windows 10 1809 x64

Por favor verifica que la versión de python que usas es la 2.7. python --version

Si tienes la versión 2.7 y la 3.*, verificar que el comando python está llamando a python27.

**Comment by Solus32** [comment]
La versión instalada de Python que uso es la 2.7.15

**Comment by 7ouma** [comment]
> @7ouma Sería de la parte Anime... Me indica que se está usando Python 3.7.2 pero le puse el que recomiendas y lo mismo; hasta hace unas semanas iba perfecto y no cambié nada a priori.
> 
> Me pasa con todos los enlaces en estos momentos...

Comprueba que se te esté llamando la versión de python correcta, abre la consola de sistema y tipea python --version

**Comment by Solus32** [comment]
Hoy acabo de checar la versión de python del sitio web y acaba de salir la versión 2.7.16

**Comment by Solus32** [comment]
C:\Users\solus\CrunchySubs>python --version
Python 2.7.15

**Comment by THeXES** [comment]
@7ouma ¡Ahora me va! ¡¡Muchas gracias Crack!! Sería por el Python entonces que estaba usando el 3.X.X

Ahora estoy usando 2.7.13; lo dicho: muchas gracias ^^

**P.d**: Como dato, uso Windows 10 vers. 1809 (x64)

**Comment by 7ouma** [comment]
> Hoy acabo de checar la versión de python del sitio web y acaba de salir la versión 2.7.16

La subversión de python 2.7 no debería de importar, solo que debe ser python 2.7, de hecho yo uso la 2.7.14 y el compañero de arriba tiene la 2.7.13.

De verdad que no se me ocurre el porqué te esté fallando el script, lo único que te falte una dependencia. 




> @7ouma ¡Ahora me va! ¡¡Muchas gracias Crack!! Sería por el Python entonces que estaba usando el 3.X.X
> 
> Ahora estoy usando 2.7.13; lo dicho: muchas gracias ^^

Bueno saber que sí está funcionado. Ya cuando tenga tiempo analizo lo del exe.

**Comment by Solus32** [comment]
Que raro, instale las versiones:

Python 2.7.15 --- Ya la tenia instalada
NodeJS LTS 10.15.3
pip install cfscrape -U

Y como salio ese error Actualize a:
Python 2.7.16  -- sigue igual con el error

pip install cfscrape -U     y me decia esto:

You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

y actualize pip 
python -m pip install --upgrade pip

La verdad no se que sea, según yo todas las dependencias ya están

**Comment by Solus32** [comment]
Si ya lo corregí, Windows no estaba guardando el archivo bien, por la codificación UTF-8, y porque era formato Unix; Ya la costumbre de usar siempre Linux, así que descargue todo el master zip.

Muchas Gracias ya esta funcionando a la perfección.
Te lo agradezco.
Saludos
